// controllers/reportController.js
import fs   from "fs";
import path from "path";
import PDFDocument from "pdfkit";

const TMP_DIR        = process.env.REPORT_TMP_DIR || "/tmp";
const PUBLIC_BASE_URL = (process.env.PUBLIC_BASE_URL || "").replace(/\/+$/, "");

// Only allow safe filenames generated by this server (hex chars + dash + dot)
const SAFE_FILENAME_RE = /^[\w.-]+$/;

const sortItems = (items) =>
  [...items].sort((a, b) => {
    const cat = String(a.category || "").localeCompare(String(b.category || ""));
    return cat !== 0 ? cat : String(a.name || "").localeCompare(String(b.name || ""));
  });

// ─── POST /api/reports/inventory-pdf ─────────────────────────────────────────
export async function generateInventoryPdf(req, res) {
  const { items = [], note = "" } = req.body || {};

  if (!Array.isArray(items) || items.length === 0) {
    return res.status(400).json({ success: false, message: "Select at least one item" });
  }

  try {
    fs.mkdirSync(TMP_DIR, { recursive: true });

    const filename = `inventory-${Date.now()}-${Math.random().toString(16).slice(2)}.pdf`;
    const filePath = path.join(TMP_DIR, filename);

    const doc    = new PDFDocument({ size: "A4", margin: 40 });
    const stream = fs.createWriteStream(filePath);

    // Pipe errors bubble to the stream error handler below
    doc.pipe(stream);

    doc.fontSize(18).text("KitchenK Store-room Inventory", { align: "center" });
    doc.moveDown();

    if (note) {
      doc.fontSize(12).text(`Note: ${note}`);
      doc.moveDown();
    }

    let i = 1;
    let lastCat = null;

    for (const it of sortItems(items)) {
      if (it.category !== lastCat) {
        lastCat = it.category;
        doc.moveDown(0.5);
        doc.fontSize(13).text(String(lastCat || "").toUpperCase(), { underline: true });
        doc.moveDown(0.2);
        doc.fontSize(12);
      }

      const brand = it.selectedBrand || "";
      const qty   = `${it.qtyNumber || ""} ${it.unit || ""}`.trim();
      const parts = [it.name || "", brand, qty].filter(Boolean).join(" | ");
      doc.text(`${i}. ${parts}`);
      i++;
    }

    doc.end();

    stream.on("finish", () => {
      const downloadUrl = `/api/reports/download/${encodeURIComponent(filename)}`;
      res.json({
        success: true,
        downloadUrl,
        absoluteDownloadUrl: PUBLIC_BASE_URL ? `${PUBLIC_BASE_URL}${downloadUrl}` : null,
      });
    });

    stream.on("error", (err) => {
      console.error("PDF stream write error:", err);
      if (!res.headersSent) {
        res.status(500).json({ success: false, message: "PDF generation failed" });
      }
    });
  } catch (err) {
    console.error("generateInventoryPdf error:", err);
    if (!res.headersSent) {
      res.status(500).json({ success: false, message: "Server error" });
    }
  }
}

// ─── GET /api/reports/download/:file ─────────────────────────────────────────
export async function downloadAndDeletePdf(req, res) {
  try {
    const rawFile = req.params.file || "";

    // Prevent path traversal — only allow safe filenames
    if (!SAFE_FILENAME_RE.test(rawFile) || rawFile.includes("..")) {
      return res.status(400).json({ success: false, message: "Invalid filename" });
    }

    const filePath = path.join(TMP_DIR, rawFile);

    if (!fs.existsSync(filePath)) {
      return res.status(404).json({ success: false, message: "File not found or already downloaded" });
    }

    res.download(filePath, "kitchenk-inventory.pdf", (err) => {
      // Always attempt cleanup after download completes (success or failure)
      try { fs.unlinkSync(filePath); } catch { /* ignore */ }
      if (err && !res.headersSent) {
        console.error("Download error:", err);
      }
    });
  } catch (err) {
    console.error("downloadAndDeletePdf error:", err);
    if (!res.headersSent) {
      res.status(500).json({ success: false, message: "Server error" });
    }
  }
}